- hosts: localhost 
  gather_facts: no
  vars: 
   - session: ''  
   - realm: 'heroes'
   - endpoint_rhsso: https://sso-cvaldezr-stage.apps.sandbox-m2.ll9k.p1.openshiftapps.com
     #- endpoint_rhsso: http://192.168.1.100:8080 
     #- endpoint_rhsso: http://138.68.151.157:8080 

  tasks:
    - name: Login 
      register: session  
      cesarvr.keycloak.login:
        username: admin
        password: admin
        endpoint: '{{endpoint_rhsso}}' 
    - debug: var=session

    - name: Reset 
      register: result
      cesarvr.keycloak.resource: 
        name: realm 
        id: 'id'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/realm.json
        state: absent

    - name: Creates a realm 
      register: result
      cesarvr.keycloak.resource: 
        name: realm 
        id: 'id'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/realm.json
        state: present    

    - name: Add Marvel Group 
      cesarvr.keycloak.resource: 
        name: groups 
        id: name
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/groups/marvel.json
        state: present    

    - name: Add DC Group 
      cesarvr.keycloak.resource: 
        name: groups 
        id: name
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/groups/dc.json
        state: present    

    - name: Adding Roles [hero, villain]   
      cesarvr.keycloak.resources_from_folder: 
        name: roles 
        id: name
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        folder: files/roles/
        state: present    

    - name: Adding Roles [hero, villain] to DC group   
      register: result
      cesarvr.keycloak.add_roles_to_group: 
        group: DC 
        roles: 
          - hero 
          - villain
        realm: 'heroes'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        state: present    

    - name: Adding Roles [hero, villain] to Marvel group   
      register: result
      cesarvr.keycloak.add_roles_to_group: 
        group: Marvel 
        roles: 
          - hero 
          - villain
        realm: 'heroes'
        token: '{{session.result.token}}'
        endpoint: https://sso-cvaldezr-stage.apps.sandbox-m2.ll9k.p1.openshiftapps.com
        state: present    
    - debug: var=result

    - name: Creates Characters from files/users/DC   
      cesarvr.keycloak.resources_from_folder: 
        name: users 
        id: 'username'
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        folder: files/users/DC/
        state: present    

          #- name: Creating Characters from files/users/Marvel   
          #cesarvr.keycloak.resources_from_folder: 
          #name: users 
          #id: 'username'
          #realm: '{{realm}}'
          #token: '{{session.result.token}}'
          #endpoint: '{{endpoint_rhsso}}' 
          #folder: files/users/Marvel/
          #state: present    

    - name: Adding Client For DC  
      cesarvr.keycloak.resource: 
        name: clients 
        id: clientId
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/clients/dc.json
        state: present   

    - name: Adding client for Marvel  
      cesarvr.keycloak.resource: 
        name: clients 
        id: clientId
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/clients/marvel.json
        state: present    

    - name: DC Heroes Joining DC Group   
      cesarvr.keycloak.join_group: 
        name: DC 
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        folder: files/users/DC/
        state: present    

    - name: DC Heroes Joining DC Group   
      cesarvr.keycloak.join_group: 
        name: DC 
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        folder: files/users/DC/
        state: present    

    - name: Adding Custom Flow
      cesarvr.keycloak.resource: 
        name: authentication 
        id: alias
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/my-custom-registration/parent-flow.json
        state: present    

    - name: Configuring Custom Registration
      cesarvr.keycloak.authentication_flow: 
        name: authentication 
        parent_flow: files/my-custom-registration/parent-flow.json
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/my-custom-registration/executors/flow-tree.json
        state: present    




