- hosts: localhost 
  gather_facts: no
  vars: 
   - session: ''  
   - realm: 'heroes'
     #- endpoint_rhsso: https://sso-cvaldezr-stage.apps.sandbox-m2.ll9k.p1.openshiftapps.com
   - endpoint_rhsso: http://192.168.1.100:8080 
     #- endpoint_rhsso: http://138.68.151.157:8080 

  tasks:
    - name: Login 
      register: session  
      cesarvr.keycloak.login:
        username: admin
        password: admin1234
        endpoint: '{{endpoint_rhsso}}' 
    - debug: var=session
    
    - name: Adding Custom Registration
      cesarvr.keycloak.authentication_flow: 
        name: authentication 
        parent_flow: files/my-custom-registration/parent-flow.json
        realm: '{{realm}}'
        token: '{{session.result.token}}'
        endpoint: '{{endpoint_rhsso}}' 
        payload: files/my-custom-registration/executors/flow-tree.json
        state: present    




